name: mewo CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            gcc \
            musl-tools \
            clang \
            lld

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc

      - name: Install MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc

      - name: Build nob (Unix)
        if: runner.os != 'Windows'
        run: |
          gcc nob.c -o nob
          ./nob

      - name: Build nob (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          gcc nob.c -o nob.exe
          ./nob.exe

      - name: Run mewo (Unix)
        if: runner.os != 'Windows'
        run: |
          ./mewo
          ./mewo release
          ./mewo install
          mewo --version
          mewo

      - name: Run mewo (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $env:vsDevCmd = Join-Path (
              & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' `
                -latest -products * `
                -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
                -property installationPath
          ) "Common7\Tools\VsDevCmd.bat"

          .\mewo.exe
          .\mewo.exe release
          .\mewo.exe install
          $env:PATH = [Environment]::GetEnvironmentVariable('PATH','User')  # Refresh PATH because powershell is stupid
          mewo --version
          mewo
